name: align build copter

on:
  workflow_dispatch:

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-copter:
    runs-on: ubuntu-22.04
    container: ardupilot/ardupilot-dev-chibios:v0.1.3
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        copter: [
            AP3-M460,
            AP3-M460-dev,
            AP3-M490,
            AP3-M490-dev,
            AP6-M460,
            AP6-M460-dev,
            AP6-M460-G3P,
            AP6-M490,
            AP6-M490-dev,
            AP6-M490-G3P,
            AP6-M6T22,
            AP6-M6T22-dev,
            AP6-M4T12-dev,
            AP6-M4T12,
            AP6v2-M460,
            AP6v2-M460-dev,
            AP6v2-M460-G3P,
            AP6v2-M490,
            AP6v2-M490-dev,
            AP6v2-M490-G3P,
            AP6v2-M6T22,
            AP6v2-M6T22-dev,
            AP6v2-M4T12,
            AP6v2-M4T12-dev,
            AP6v2-M4P,
            AP6v2-M4P-dev,
            AP6v2-M450,
            AP6v2-M450-dev,
        ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: align build
        shell: bash
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          PATH="/usr/lib/ccache:/opt/gcc-arm-none-eabi-10/bin:$PATH"
          PATH="/github/home/.local/bin:$PATH"
          ./waf configure --board ${{matrix.copter}}
          ./waf clean
          ./waf copter

      - name: upload apj
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.copter}}
          path: build/${{matrix.copter}}/bin/arducopter.apj

  build-heli:
    runs-on: ubuntu-22.04
    container: ardupilot/ardupilot-dev-chibios:v0.1.3
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        heli: [
            AP6v2-E1,
            AP6v2-E1-dev,
            AP6v2-TB70,
            AP6v2-TB70-AT12,
            AP6v2-TB70-dev,
        ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: align build
        shell: bash
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          PATH="/usr/lib/ccache:/opt/gcc-arm-none-eabi-10/bin:$PATH"
          PATH="/github/home/.local/bin:$PATH"
          ./waf configure --board ${{matrix.heli}}
          ./waf clean
          ./waf heli

      - name: upload apj
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.heli}}
          path: build/${{matrix.heli}}/bin//arducopter-heli.apj
  
  upload:
    runs-on: ubuntu-22.04
    needs: [build-copter, build-heli]

    steps:
      - name: create align-build dir
        run: mkdir -p align-build

      - name: download apj
        uses: actions/download-artifact@v4
        with:
          path: align-build

      - name: create ZIP align-build
        run: |
          zip -r align-build/align-build-copter.zip align-build/

      - name: upload ZIP align-build
        uses: actions/upload-artifact@v4
        with:
          name: align-build-copter
          path: align-build/align-build-copter.zip

      - name: cleanup
        if: always()
        run: |
          rm -rf align-build
